name: Autograding Tests
on:
  push:
  repository_dispatch:
permissions:
  checks: write
  actions: read
  contents: read
jobs:
  any-debug-wf:
    if: github.actor != 'github-classroom[bot]'        
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Check if custom YAML file exists
        run: |
          if [[ ! -f .github/workflows/08-expressions.yaml ]]; then
            echo "Error: Custom YAML (08-expressions.yaml) workflow file is missing!"
            exit 1
          fi
          echo "Custom YAML file 08-expressions.yaml exists."

      - name: Check for expected workflow triggers
        run: |
          if ! grep -q "workflow_dispatch" .github/workflows/08-expressions.yaml; then
            echo "Error: 'workflow_dispatch' trigger is missing!"
            exit 1
          fi
          echo "'workflow_dispatch' trigger is defined."

      - name: Verify jobs in the YAML file
        run: |
          if ! grep -q "debug-check" .github/workflows/08-expressions.yaml; then
            echo "Error: 'debug-check' job is missing!"
            exit 1
          fi
          if ! grep -q "functions-pr-data" .github/workflows/08-expressions.yaml; then
            echo "Error: 'functions-pr-data' job is missing!"
            exit 1
          fi
          echo "Both 'debug-check' and 'functions-pr-data' jobs are present."

      - name: Verify steps in 'debug-check' job
        run: |
          if ! grep -q "Print Debug Info" .github/workflows/08-expressions.yaml; then
            echo "Error: 'Print Debug Info' step is missing!"
            exit 1
          fi
          if ! grep -q "Triggered from Main" .github/workflows/08-expressions.yaml; then
            echo "Error: 'Triggered from Main' step is missing!"
            exit 1
          fi
          echo "Steps in 'debug-check' job are correct."

      - name: Verify steps in 'functions-pr-data' job
        run: |
          if ! grep -q "Print PR data" .github/workflows/08-expressions.yaml; then
            echo "Error: 'Print PR data' step is missing!"
            exit 1
          fi
          if ! grep -q "Bug Check" .github/workflows/08-expressions.yaml; then
            echo "Error: 'Bug Check' step is missing!"
            exit 1
          fi
          if ! grep -q "Sleep and Cancel" .github/workflows/08-expressions.yaml; then
            echo "Error: 'Sleep and Cancel' step is missing!"
            exit 1
          fi
          echo "Steps in 'functions-pr-data' job are correct."

      - name: Ensure that the YAML contains expressions
        run: |
          if ! grep -q "expression" .github/workflows/08-expressions.yaml; then
            echo "Error: The file does not contain any expressions (e.g., 'expression || default_value')."
            exit 1
          fi
          echo "Expressions are correctly defined in the workflow."

      - name: Check if the workflow includes Mermaid diagram
        run: |
          if ! grep -q "graph TD" .github/workflows/08-expressions.yaml; then
            echo "Error: Mermaid diagram is missing in the YAML workflow!"
            exit 1
          fi
          echo "Mermaid diagram is present in the workflow."

      - name: Check for valid input definitions in workflow_dispatch
        run: |
          if ! grep -q "inputs" .github/workflows/08-expressions.yaml; then
            echo "Error: 'inputs' definition is missing in workflow_dispatch!"
            exit 1
          fi
          echo "'inputs' section is defined in workflow_dispatch."

    #  - name: Verify successful execution of workflow using GitHub API
    #    uses: peter-evans/workflow-dispatch@v1
    ##    with:
    #      workflow: .github/workflows/08-expressions.yaml
    #      token: ${{ secrets.GITHUB_TOKEN }}
    #      ref: ${{ github.sha }}
   #       inputs: |
    #        debug: 'true'
   #     id: workflow_run

   
            
      - name: Get WF 
        id: get-debug-wf        
        uses: actions/github-script@v6
        with:
          script: |
            const workflow = '07-contexts.yaml' ;
            const owner = context.repo.owner;
            const repo = context.repo.repo;
            const workflows = await github.rest.actions.listWorkflowRuns({
                  owner,
                  repo,
                  workflow_id: workflow,
                  per_page: 1,
                  status: 'success'                
                });       

             const wfObj = workflows.data.workflow_runs.find(wf => 
              wf.name === "07 - Contexts | DEBUG - true"             
            );       
            core.setOutput('executed', wfObj != 'undefined');
            console.log(wfObj != 'undefined')   
          result-encoding: string
